#!/usr/bin/env /usr/bin/python3
import sys
import os

# Ensure repo root is on python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.main import main

if __name__ == "__main__":
    sys.exit(main())
